name       : mediaelch
version    : 2.6.6
release    : 4
source     :
    - git|https://github.com/Komet/MediaElch.git : 2829f2d0ed0e692b82c143a0c670d77d489645a3
license    : LGPL-3.0
component  : desktop.multimedia
summary    : Media Manager for Kodi
description: |
    MediaElch is a MediaManager for Kodi. Information about Movies, TV Shows, Concerts and Music are stored as nfo files. Fanarts are downloaded automatically from fanart.tv. Using the nfo generator, MediaElch can be used with other MediaCenters as well.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(libmediainfo)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
