name       : mediaelch
version    : 2.4.2
release    : 3
source     :
    - git|https://github.com/Komet/MediaElch.git : ed005f45684375c515499be150051dd802b05a2e
license    : LGPL-3.0
component  : desktop.multimedia
summary    : Media Manager for Kodi
description: |
    MediaElch is a MediaManager for Kodi. Information about Movies, TV Shows, Concerts and Music are stored as nfo files. Fanarts are downloaded automatically from fanart.tv. Using the nfo generator, MediaElch can be used with other MediaCenters as well.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(libmediainfo)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
